name:  TEST

on:
  pull_request:
    branches:
      - dev
      - stg
      - main
    types:
      - opened
      - reopened
      - synchronize

env: 
  TEST_VARIABLE: This is a test variable
  ENVIRONMENT: |-
    ${{
      github.base_ref == 'dev' && 'environments/dev' ||
      github.base_ref == 'stg' && 'environments/stg' ||
      github.base_ref == 'main' && 'environments/prod'
    }}



jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
    - name: checkout test  
      uses: actions/checkout@v4

# ${{ (github.base_ref == 'dev' && 'dev') || (github.base_ref) ||  (github.base_ref == 'main' && 'prod') || 'INVALID' }}


